# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: alorlea

description: Stylish Jekyll Theme
author:
  name: Alberto Lorente Leal
  email: a.lorenteleal@gmail.com
  github: alorlea
  twitter: alorlea
  linkedin: in/alorlea
  bio: Software engineer with knowledge in telecommunications, distributed computing and scalable systems. High performance? Availability? You name it!
       Super passionate with everyday challenges in areas of scalability, algorithms and distributed services. Big data and its technologies are my attraction (right now I am looking forward Hadoop, Spark, Cassandra...)
       Music and videogame lover with keen interest in new cultures and languages. Also I like to hack from time to time.
  email_md5: a2517b8754098f7e193d6920b61fe154

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
